### ISSUE TITLE
The linting doesn't work

### ISSUE THREAD

**Issue by Kruemmelspalter** [JustDoom/anything-minecraft#10]
It gives me errors:
```
    /projects/anything-minecraft    german +1 ?1  npm run lint                                                                                                                1 ✘ 

> anything-minecraft@1.0.0 lint /projects/anything-minecraft
> npm run lint:markdown && npm run lint:prettier


> anything-minecraft@1.0.0 lint:markdown /projects/anything-minecraft
> markdownlint '**/*.md' --ignore node_modules

tutorials/de_de/Server_Einrichtung.md:64 MD031/blanks-around-fences Fenced code blocks should be surrounded by blank lines [Context: "```txt"]
tutorials/de_de/Server_Einrichtung.md:92 MD031/blanks-around-fences Fenced code blocks should be surrounded by blank lines [Context: "```dockerfile"]
tutorials/de_de/Server_Einrichtung.md:101 MD031/blanks-around-fences Fenced code blocks should be surrounded by blank lines [Context: "```"]
tutorials/de_de/Server_Einrichtung.md:114 MD031/blanks-around-fences Fenced code blocks should be surrounded by blank lines [Context: "```yml"]
tutorials/de_de/Server_Einrichtung.md:122 MD031/blanks-around-fences Fenced code blocks should be surrounded by blank lines [Context: "```"]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! anything-minecraft@1.0.0 lint:markdown: `markdownlint '**/*.md' --ignore node_modules`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the anything-minecraft@1.0.0 lint:markdown script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kruemmelspalter/.npm/_logs/2021-01-26T12_09_08_425Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! anything-minecraft@1.0.0 lint: `npm run lint:markdown && npm run lint:prettier`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the anything-minecraft@1.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kruemmelspalter/.npm/_logs/2021-01-26T12_09_08_442Z-debug.log
```

Debug Log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'lint' ]
2 info using npm@6.14.11
3 info using node@v15.6.0
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle anything-minecraft@1.0.0~prelint: anything-minecraft@1.0.0
6 info lifecycle anything-minecraft@1.0.0~lint: anything-minecraft@1.0.0
7 verbose lifecycle anything-minecraft@1.0.0~lint: unsafe-perm in lifecycle true
8 verbose lifecycle anything-minecraft@1.0.0~lint: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/projects/anything-minecraft/node_modules/.bin:/home/kruemmelspalter/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
9 verbose lifecycle anything-minecraft@1.0.0~lint: CWD: /projects/anything-minecraft
10 silly lifecycle anything-minecraft@1.0.0~lint: Args: [ '-c', 'npm run lint:markdown && npm run lint:prettier' ]
11 silly lifecycle anything-minecraft@1.0.0~lint: Returned: code: 1  signal: null
12 info lifecycle anything-minecraft@1.0.0~lint: Failed to exec lint script
13 verbose stack Error: anything-minecraft@1.0.0 lint: `npm run lint:markdown && npm run lint:prettier`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (node:events:379:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (node:events:379:20)
13 verbose stack     at maybeClose (node:internal/child_process:1065:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:296:5)
14 verbose pkgid anything-minecraft@1.0.0
15 verbose cwd /projects/anything-minecraft
16 verbose Linux 5.10.7-3-MANJARO
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "lint"
18 verbose node v15.6.0
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error anything-minecraft@1.0.0 lint: `npm run lint:markdown && npm run lint:prettier`
22 error Exit status 1
23 error Failed at the anything-minecraft@1.0.0 lint script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
So I can't commit because git automatically runs it

**Comment by Kruemmelspalter** [comment]
Ok the problem is in `lint:markdown`

**Comment by Kruemmelspalter** [comment]
Ok I just had to manually add newlines before and after code blocks
